version: '3.8'

services:
  app:
    build: .
    container_name: sunum-app
    environment:
      SPRING_APPLICATION_NAME: sunum
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3307/sunum
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    ports:
      - "8080:8080"
